# ----------------------------------------------------------------
# Propiedades que deben estar disponibles para toda la aplicación
# más allá de los plugins de inicialización.
# ----------------------------------------------------------------

#Path para obtener imagen logo bbva en caratula.
rendicion.image.caratula =/desa/apps/was/ears/rendiciones90.ear/transfer/caratula/logoSUMINISTRO.png

#Path para la carpeta temporal de generacion de BarCode
rendicion.image.idu =/desa/apps/was/ears/rendiciones90.ear/transfer/caratula

#Link para nuevo llamado a thuban
rendicion.link.thuban = http://wstamdesa.arg.igrupobbva/thuban-web/secure/search.zul?clase=CTA-RENDICIONES&indexes=N_FACTURA=

#Variable que determina la visiblidad del modal del anuncio general.
modal.inicial=false

esb.thuban.user=UDESVADI
esb.thuban.pass=valija18
esb.thuban.clase.documental=CTA-RENDICIONES