# ----------------------------------------------------------------
# Propiedades que deben estar disponibles para toda la aplicación
# más allá de los plugins de inicialización.
# ----------------------------------------------------------------
#Path donde alojará los archivos cargados para thuban.
rendicion.aviso.path =/prod/apps/was/ears/rendiciones.ear/transfer/thubanFiles/

#Path para obtener imagen logo bbva en caratula.
rendicion.image.caratula =/prod/apps/was/ears/rendiciones.ear/transfer/caratula/logoSUMINISTRO.png

#Path para la carpeta temporal de generacion de BarCode
rendicion.image.idu =/prod/apps/was/ears/rendiciones.ear/transfer/caratula

#Link para nuevo llamado a thuban
rendicion.link.thuban = http://wstamtest.arg.igrupobbva/thuban-web/secure/search.zul?clase=CTA-RENDICIONES&indexes=N_FACTURA=

#Nombre que ira al comienzo del archivo que se va a subir a thuban (CTAS_CRE_A000170737_A103555_118_2016-08-31-12.37.45.pdf)
rendicion.aviso.rename.archivo = CTAS_CRE_

#Configuracion de thuban
esb.thuban.user=UDESVADI
esb.thuban.pass=${thuban.pass}
esb.thuban.clase.documental=CTA-RENDICIONES
