#############################################################################
# Clases de inicialización de la aplicación web, se separan con ;           #
# Todas los plugins de inicialización de la aplicación, los mismos deben    #
# extender la clase abstracta ar.com.bbva.initPlugins.BasicInitPlugin       #
#############################################################################
#initClasses=ar.com.bbva.web.initPlugins.Log4jInitPlugin;ar.com.bbva.web.initPlugins.SAMInitPlugin;ar.com.bbva.web.initPlugins.DAOFactoryInitPlugin;ar.com.bbva.web.initPlugins.SAMWebAppInitPlugin
initClasses=ar.com.bbva.web.initPlugins.Log4jInitPlugin;ar.com.bbva.web.initPlugins.SAMInitPlugin;ar.com.bbva.initPlugins.SamWsNetInitPlugin;ar.com.bbva.web.initPlugins.SAMWebAppInitPlugin
#ar.com.bbva.web.initPlugins.SAMWSInitPlugin
# NOTA:
# Si no se va a emplear SAM eliminar el plugin de inicialización y las líneas
# de configuración que se encuentran más abajo en este archivo...
#
#############################################################################
# Archivos de propiedades separados con ; disponibles unicamente para los   #
# plugins de inicialización, después no quedan visibles para el resto de la #
# aplicación por seguridad.                                                 #
#############################################################################
#initPropertyFiles=${syscfgpath}/claves.properties;
# initPropertyFiles=${syscfgpath}/clavesLocalHost.properties;
#
#############################################################################
# configuración de parametros para las rutinas de cifrado - SI              #
#############################################################################
#En los entornos de desarrollo WAS configurar:
#cipher.parametersFile=/desa/apps/SI/scKey.<nombre_aplicacion>
#Simulación en entorno local:
#cipher.parametersFile=${syscfgpath}/scKey
#
#############################################################################
# Archivos de propiedades que debe levantar al contexto, separados con ;    #
# Quedan disponibles para el resto de la aplicación como atributos en el    #
# ServletContext. Si se indica un directorio levanta todos los .properties  #
#############################################################################
propertyFiles=${syscfgpath}/suministros.sys.properties;${syscfgpath}/../cfg;
#
#############################################################################
# configuración de log4j                                                    #
#############################################################################
# Archivo de configuracion xml
log4j.file=${syscfgpath}/log4j.xml
# path donde se dejarán los logs
log4j.logPath=/log/prod/apps/was/rendiciones
log4j.logFile=suministros4j.log
#
#############################################################################
# configuración de SAM                                                      #
#############################################################################
# Archivo de configuración de SAM
sam.xmlFile=${syscfgpath}/../cfg/sam.xml
sam.cfgs=${syscfgpath}/../cfg
#archivo de configuracion de Datasource Factory
#sam.xmlDFFile=${syscfgpath}/sam.DBCP.xml
##archivo de configuracion de los Web Services expuestos por SAM
#sam.xmlWSFile=${syscfgpath}/../cfg/sam-services.xml
#
#############################################################################
# configuración de DAO apuntando a las implementaciones de SAM              # 
#############################################################################
#daoFactory.classPrefix=SAM
#daoFactory.package=.impl
#
#############################################################################
# Implementaciones de los objetos IWebApplication e IWebClient              # 
#############################################################################
web.webAppClass=ar.com.bbva.web.impl.SAMWebApplication
web.webClientClass=ar.com.bbva.web.impl.SAMWebClient
web.appName=suministros
#
#############################################################################
# Parametros para el filtro de seguridad de control del login               #
# para el parámetro noLoginPageExpr tiene prioridad el que está configurado #
# en el web.xml                                                             #
# web.login				ruta a la página de login. Por defecto login.jsp    # 
# web.error				ruta a la página de error genérica.                 #
#                       Por defecto error.jsp                               # 
# web.noLoginPageExpr	expresión que indica cómo reconocer a las páginas   #
#                       que no requieren que un usuario esté logueado para  #
#                       ejecutarse, y que no son ni la página de login ni   #
#                       la de error genérico                                # 
#                       Por defecto "*.NL.*"                                # 
# web.doTiming          si está en true loguea el tiempo demorado en        #
#                       procesar una página. Por defecto false              #
#############################################################################
web.login=login.jsp
web.error=error.jsp
web.doTiming=true

#####################################################################
# Propiedades usadas por el ARQ_SAM_plugin_bbvaPaq                  #
#####################################################################
###
# APLICACION
###
#aplicacion=AGENDA
aplicacion=SUMINISTROS
###
# MODULO
###
#DESA 
#modulo=SUMINISTROS
#SUMINISTROS_CICS5 que apunta al bridge PS9 de CICS5
#SUMINISTROS_CICS7 que apunta al bridge PS9 de CICS7
#TEST
modulo=SUMINISTROS_CICS5
#PROD 
#modulo=SUMINISTROS


# En milisegundos
bbvaPaq.timeout=120000
# URL del endpoint en DESARROLLO
#bbvaPaq.conSoaTcs.endpoint=http://dvi006-muleesb.arg.igrupobbva:8100/ServicioInicial
# URL del endpoint en TESTING
bbvaPaq.conSoaTcs.endpoint=http://dvi006-muleesb.arg.igrupobbva:9100/ServicioInicial
# URL del endpoint en PRODUCCION
#bbvaPaq.conSoaTcs.endpoint=http://pvi062-muleesb.arg.igrupobbva:8100/ServicioInicial

initPropertyFiles=${syscfgpath}/claves.properties;
cipher.parametersFile=/prod/apps/SI/scKeyT.valijadig
